db "basketball", 0
db "football", 0
db "volleyball", 0
db "tennis", 0
db "baseball", 0
db "table", 0
db "chair", 0
db "television", 0
db "couch", 0
db "window", 0
db "closet", 0
db "capybara", 0
db "otter", 0
db "snail", 0
db "giraffe", 0
db "rhinoceros", 0
db "monkey", 0
db "gorilla", 0
db "penguin", 0
db "flamingo", 0
db "cockroach", 0
db "chameleon", 0
db "dolphin", 0
db "squirrel", 0
db "hedgehog", 0
db "hippopotamus", 0
db "elephant", 0
db "kangaroo", 0
db "octopus", 0
db "donkey", 0
db "pangolin", 0
db "platypus", 0
db "scorpion", 0
db "salamander", 0
db "peacock", 0
db "wombat", 0
db "buffalo", 0
db "python", 0
db "windows", 0
db "linux", 0
db "android", 0
db "cybercrime", 0
db "processor", 0
db "assembly", 0
db "cheese", 0
db "pizza", 0
db "water", 0
db "apple", 0
db "cucumber", 0
db "eggplant", 0
db "rhubarb", 0
db "salad", 0
db "rice", 0
db "mushroom", 0
db "lemon", 0
db "coconut", 0
db "avacado", 0
db "banana", 0
db "cherry", 0
db "melon", 0
db "potato", 0
db "pumpkin", 0
db "onion", 0
db "carrot", 0
db "bread", 0
db "hamburger", 0
db "lobster", 0
db "salmon", 0
db "chocolate", 0
db "noodles", 0
db "sandwich", 0
db "bacon", 0
db "beer", 0
db "turkey", 0
db "wine", 0
db "cookie", 0
db "donut", 0
db "fondu", 0
db "lasagna", 0
db "pepperoni", 0
db "england", 0
db "india", 0
db "germany", 0
db "switzerland", 0
db "italy", 0
db "france", 0
db "sweden", 0
db "europe", 0
db "austria", 0
db "finland", 0
db "croatia", 0
db "greece", 0
db "russia", 0
db "portugal", 0
db "norway", 0
db "poland", 0
db "africa", 0
db "asia", 0
db "japan", 0
db "china", 0
db "korea", 0
db "trap", 0
db "abyss", 0
db "piano", 0
db "violin", 0
db "flute", 0
db "guitar", 0
db "bongo", 0
db "lute", 0
db "trumpet", 0
db "ukulele", 0
db "bagpipe", 0
db "galaxy", 0
db "star", 0
db "moon", 0
db "mars", 0
db "jupiter", 0
db "mercury", 0
db "venus", 0
db "earth", 0
db "saturn", 0
db "uranus", 0
db "neptune", 0
db "hangman", 0
